CoreApp15_04/Models/ErrorViewModel.cs
using System;

namespace CoreApp15_04.Models
{
	public class ErrorViewModel
	{
		public string RequestId { get; set; }

		public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
	}
}

CoreApp15_04/Models/Post.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CoreApp15_04_Instagram.Models
{
	public class Post
	{
		public Guid Id { get; set; }
		public string Title { get; set; }
		public virtual ICollection<PostTag> PostTag { get; set; }
		public string CommaSeparatedPhotoPaths { get; set; }

		public Post()
		{
			Id = Guid.NewGuid();
			this.PostTag = new HashSet<PostTag>();
		}
	}
}

CoreApp15_04/Models/PostTag.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CoreApp15_04_Instagram.Models
{
	public class PostTag
	{
		public Guid PostId { get; set; }
		public int TagId { get; set; }

		public Post Post { get; set; }
		public Tag Tag { get; set; }
	}
}

CoreApp15_04/Models/Tag.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CoreApp15_04_Instagram.Models
{
	public class Tag
	{
		public int Id { get; set; }
		public string Name { get; set; }

		public virtual ICollection<PostTag> PostTag { get; set; }

		public Tag()
		{
			this.PostTag = new HashSet<PostTag>();
		}
	}
}

CoreApp15_04/ViewModels/AddPostViewModel.cs
using Microsoft.AspNetCore.Http;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace CoreApp15_04_Instagram.ViewModels
{
	public class AddPostViewModel
	{
		[Required]
		public string Title { get; set; }
		[Required]
		public string CommaSeparatedTags { get; set; }
		[Required]
		public List<IFormFile> Photos { get; set; }
	}
}

CoreApp15_04/ViewModels/DisplayPostViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CoreApp15_04_Instagram.ViewModels
{
	public class DisplayPostViewModel
	{
		public string Title { get; set; }
		public List<string> Tags { get; set; }
		public List<string> PhotoPaths { get; set; }
	}
}

CoreApp15_04/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using CoreApp15_04.Models;

namespace CoreApp15_04.Controllers
{
	public class HomeController : Controller
	{
		public IActionResult Index()
		{
			return View();
		}

		public IActionResult About()
		{
			ViewData["Message"] = "Your application description page.";

			return View();
		}

		public IActionResult Contact()
		{
			ViewData["Message"] = "Your contact page.";

			return View();
		}

		public IActionResult Privacy()
		{
			return View();
		}

		[ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
		public IActionResult Error()
		{
			return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
		}
	}
}

CoreApp15_04/Controllers/PostController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using CoreApp15_04_Instagram.Models;
using CoreApp15_04_Instagram.ViewModels;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using CoreApp15_04_Instagram.DAL;

namespace CoreApp15_04_Instagram.Controllers
{
	public class PostController : Controller
	{
		public static List<Post> PublishedPosts { get; set; } = new List<Post>();

		private IHostingEnvironment _env;
		private IAlaInstagramData _alaInstagramData;

		public PostController(IHostingEnvironment env)
		{
			_alaInstagramData = new DbAlaInstagramData();
			_env = env;
		}

		// GET: Post
		public ActionResult Index()
		{
			//Auto Mapper Poszukac info
			PublishedPosts = _alaInstagramData.GetAll().ToList();
			var displayPostViewModels = PublishedPosts.Select(n => new DisplayPostViewModel
			{
				Title = n.Title,
				PhotoPaths = n.CommaSeparatedPhotoPaths.Split(',').ToList(),
				Tags = _alaInstagramData.GetTags(n).Select(x => x.Name).ToList()
			});

			return View(displayPostViewModels);
		}

		// GET: Post/Create
		public ActionResult Create()
		{
			return View();
		}

		// POST: Post/Create
		[HttpPost]
		[ValidateAntiForgeryToken]
		public ActionResult Create(AddPostViewModel addPostViewModel)
		{
			try
			{
				if (ModelState.IsValid)
				{
					// 1. Zapis plik na dysku TAK
					// 2. Zapis post do bazy TAK
					// 3. Przesuwanie zdjec jesli jest przeslane wiecej zdjec TAK/NIE
					// 4. Sposob przeslania wiecej zdjec na raz do jednego posta TAK
					// 5. Wyswietlanie podgladu zdjec przed wyslalem TAK
					// 6. Sposob usuniecia zdjecia z wysylanych w podgladzie NIE

					var uploadFolder = "Upload";
					var savePhotoPath = Path.Combine(_env.WebRootPath, uploadFolder);

					List<string> paths = new List<string>();

					foreach (IFormFile photo in addPostViewModel.Photos)
					{
						string fileName = photo.FileName;
						var savePath = Path.Combine(savePhotoPath, fileName);
						using (var photoSave = new FileStream(savePath, FileMode.Create))
						{
							photo.CopyTo(photoSave);
						}
						paths.Add("/" + uploadFolder + "/" + fileName);
					}

					//TODO: zapis do bazy (z migracjami)
					var newPost = new Post
					{
						Title = addPostViewModel.Title,
						//PostTag = addPostViewModel.CommaSeparatedTags.Split(',')
						//.Select(t => new Tag { Name = t }).ToList(),
						CommaSeparatedPhotoPaths = String.Join(',', paths)
					};

					foreach (var tagName in addPostViewModel.CommaSeparatedTags.Split(','))
					{
						if (_alaInstagramData.GetTagByName(tagName) == null)
						{
							newPost.PostTag.Add(new PostTag
							{
								Post = newPost,
								Tag = new Tag { Name = tagName }
							}
						);
						}
						else
						{
							newPost.PostTag.Add(new PostTag
							{
								Post = newPost,
								TagId = _alaInstagramData.GetTagByName(tagName).Id
							}
						);
						}
						
					}

					PublishedPosts.Add(newPost);
					_alaInstagramData.SaveAlaInstagramPost(newPost);

					return RedirectToAction(nameof(Index));
				}
				return View(addPostViewModel);
			}
			catch (Exception ex)
			{
				return View();
			}
		}
	}
}

CoreApp15_04/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<p>Use this area to provide additional information.</p>

CoreApp15_04/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

CoreApp15_04/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div id="myCarousel" class="carousel slide" data-ride="carousel" data-interval="6000">
    <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
    </ol>
    <div class="carousel-inner" role="listbox">
        <div class="item active">
            <img src="~/images/banner1.svg" alt="ASP.NET" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Learn how to build ASP.NET apps that can run anywhere.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525028&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/banner2.svg" alt="Visual Studio" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    There are powerful new features in Visual Studio for building modern web apps.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525030&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/banner3.svg" alt="Microsoft Azure" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Learn how Microsoft's Azure cloud platform allows you to build, deploy, and scale web apps.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525027&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
    </div>
    <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>

<div class="row">
    <div class="col-md-3">
        <h2>Application uses</h2>
        <ul>
            <li>Sample pages using ASP.NET Core MVC</li>
            <li>Theming using <a href="https://go.microsoft.com/fwlink/?LinkID=398939">Bootstrap</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>How to</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=398600">Add a Controller and View</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699315">Manage User Secrets using Secret Manager.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699316">Use logging to log a message.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699317">Add packages using NuGet.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699319">Target development, staging or production environment.</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>Overview</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=518008">Conceptual overview of what is ASP.NET Core</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699320">Fundamentals of ASP.NET Core such as Startup and middleware.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=398602">Working with Data</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=398603">Security</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699321">Client side development</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699322">Develop on different platforms</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699323">Read more on the documentation site</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>Run &amp; Deploy</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=517851">Run your app</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=517853">Run tools such as EF migrations and more</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=398609">Publish to Microsoft Azure Web Apps</a></li>
        </ul>
    </div>
</div>

CoreApp15_04/Views/Post/Create.cshtml
@model CoreApp15_04_Instagram.ViewModels.AddPostViewModel

@{
	ViewData["Title"] = "Create";
}

<h2>Hello in Ala Instagram app</h2>

<h4>Add Post</h4>
<hr />
<div class="row">
	<div class="col-md-12">
		<form id="fileupload" asp-action="Create" enctype="multipart/form-data">
			<div asp-validation-summary="ModelOnly" class="text-danger"></div>
			<div class="form-group col-md-4">
				<label asp-for="Title" class="control-label"></label>
				<input asp-for="Title" class="form-control" />
				<span asp-validation-for="Title" class="text-danger"></span>
			</div>
			<div class="form-group col-md-4">
				<label asp-for="CommaSeparatedTags" class="control-label"></label>
				<input asp-for="CommaSeparatedTags" class="form-control" data-role="tagsinput" />
				<span asp-validation-for="CommaSeparatedTags" class="text-danger"></span>
			</div>
			<div class="form-group">
				<label asp-for="Photos" class="control-label"></label>
				<input asp-for="Photos" type="file"  multiple class="inputfile" id="file">
				<label for="file" class="btn btn-success">
					<span>Add file...</span>
				</label>
				<span asp-validation-for="Photos" class="text-danger"></span>
			</div>
			<div class="container">
				<div class="row" id="files"></div>
			</div>

			<div class="form-group">
				<input type="submit" value="Publish" class="btn btn-primary" />
			</div>
		</form>
	</div>
</div>

<div>
	<a asp-action="Index">Back to List</a>
</div>

@section Scripts {
	@{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

CoreApp15_04/Views/Post/Index.cshtml
@model IEnumerable<CoreApp15_04_Instagram.ViewModels.DisplayPostViewModel>

@{
	ViewData["Title"] = "Index";
}

<h2>Your posts</h2>

<p>
	<a asp-action="Create">Add new post</a>
</p>
<div class="row">
	@foreach (var post in Model)
	{
		<div class="col-sm-12 col-md-6 col-lg-4">
			<h3>@post.Title</h3>
			<div id="@post.Title" class="carousel slide" data-ride="carousel">
				<div class="carousel-inner">
					@{
						var first = true;
					}
					@foreach (var photo in post.PhotoPaths)
					{
						<div class="carousel-item @(first?Html.Raw("active"):Html.Raw(""))">
							<img class="d-block w-100" src="@photo" alt="@photo">
						</div>
						first = false;
					}
				</div>
				<a class="carousel-control-prev" href="#@post.Title" role="button"
				   data-slide="prev">
					<span class="carousel-control-prev-icon" aria-hidden="true"></span>
					<span class="sr-only">Previous</span>
				</a>
				<a class="carousel-control-next" href="#@post.Title" role="button"
				   data-slide="next">
					<span class="carousel-control-next-icon" aria-hidden="true"></span>
					<span class="sr-only">Next</span>
				</a>
			</div>
			@foreach (var tag in post.Tags)
			{
				<span class="btn btn-primary">@tag</span>
			}
		</div>
	}
</div>

CoreApp15_04/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CoreApp15_04</title>

	<environment include="Development">
		@*<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />*@
		<link href="~/css/bootstrap.css" rel="stylesheet" />
		<link rel="stylesheet" href="~/css/site.css" />
		@*<link href="~/css/bootstrap-tagsinput.css" rel="stylesheet" />*@
		<link href="~/css/tagsinput.css" rel="stylesheet" />
		<link href="~/css/Custom.css" rel="stylesheet" />
	</environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
	<nav class="navbar navbar-dark bg-dark sticky-top navbar-expand-md">
		<div class="container">
			<div class="navbar-header">
				<button type="button" class="navbar-toggler" data-toggle="collapse" data-target=".navbar-collapse">
					<span class="navbar-toggler-icon"></span>
				</button>
				<a asp-area="" asp-controller="Post" asp-action="Index" class="navbar-brand">AlaInstagram</a>
			</div>
			<div class="navbar-collapse collapse">
				<ul class="nav navbar-nav">
					<li><a asp-area="" asp-controller="Post" asp-action="Index" class="mr-4">Posts</a></li>
					<li><a asp-area="" asp-controller="Post" asp-action="Create" class="mr-4">Create</a></li>
				</ul>
			</div>
		</div>
	</nav>

    <partial name="_CookieConsentPartial" />

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2019 - CoreApp15_04</p>
        </footer>
    </div>

	<environment include="Development">
		<script src="~/lib/jquery/dist/jquery.js"></script>
		@*<script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>*@
		<script src="~/js/bootstrap.js"></script>
		<script src="~/js/site.js" asp-append-version="true"></script>
		@*<script src="~/lib/bootstrap-tagsinput.js"></script>*@
		<script src="~/lib/tagsinput.js"></script>
		<script src="~/js/jquery.js"></script>
		<script src="~/js/ImagePreview.js"></script>
	</environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-aJ21OjlMXNL5UyIl/XNwTMqvzeRMZH2w8c5cRVpzpU8Y5bApTppSuUkhZXN0VxHd">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>